name: Publish to PyPI

"on":
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # Required for PyPI trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.x"
        python-version: 3.11
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Build
      run: |
        uv build

    - name: Publish
      run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
